"use client";
type Resource={key:string;name:string;enabled:boolean;data:Record<string,unknown>};
export type Node={kind:"trigger"|"condition"|"wait"|"email"|"sms"|"end";label:string;detail?:string};
export function flowNodes(resource:Resource):Node[]{
 const key=resource.key;
 if(key==="abandoned-cart")return [{kind:"trigger",label:"Checkout Started",detail:"When a customer starts checkout"},{kind:"condition",label:"Checkout started in last 3 days?",detail:"Only continue for a recent checkout"},{kind:"condition",label:"Can receive SMS?",detail:"Email and SMS consent are checked separately"},{kind:"wait",label:"Wait 30 minutes",detail:"SMS branch only"},{kind:"sms",label:"SMS reminder",detail:"Only for eligible SMS subscribers"},{kind:"wait",label:"Wait 3 hours"},{kind:"email",label:"Email #1 · Soft Push"},{kind:"wait",label:"Wait 1 day"},{kind:"condition",label:"Placed an order since checkout?"},{kind:"email",label:"Email #2 · Another Soft Push",detail:"Yes branch"},{kind:"email",label:"Email #2 · Discount Offer",detail:"No branch"},{kind:"end",label:"End"}];
 if(key==="welcome")return [{kind:"trigger",label:"Added to Mailable Subscribers"},{kind:"email",label:"Welcome Email #1"},{kind:"condition",label:"Placed order 0–25 days ago?"},{kind:"wait",label:"Wait 3 days",detail:"No branch"},{kind:"email",label:"FOMO Email #1"},{kind:"condition",label:"Zero orders in last week?"},{kind:"email",label:"FOMO Email #2",detail:"Yes branch"},{kind:"wait",label:"Wait 3 days · 5:00 PM"},{kind:"email",label:"Social Media message"},{kind:"end",label:"End"}];
 if(key==="b2b-welcome")return [{kind:"trigger",label:"Added to B2B Customers",detail:"Shopify customer tag contains b2b"},{kind:"email",label:"Wholesale welcome email"},{kind:"end",label:"End"}];
 if(key==="low-stock")return [{kind:"trigger",label:"Low Stock Alert",detail:"Inventory state crosses the configured threshold"},{kind:"condition",label:"Product is below threshold?",detail:"Default threshold: 5"},{kind:"sms",label:"Internal low-stock alert",detail:"Transactional channel"},{kind:"end",label:"End"}];
 return [{kind:"trigger",label:"Delivery date received",detail:"Trusted delivery event"},{kind:"condition",label:"Delivery date is valid?"},{kind:"wait",label:"Wait until 24 hours before delivery"},{kind:"email",label:"Delivery upsell email"},{kind:"end",label:"End"}];
}
const icon={trigger:"⚡",condition:"⑂",wait:"◷",email:"✉",sms:"▣",end:"•"};
export function FlowMap({resource,onNodeClick}:{resource:Resource;onNodeClick?:(node:Node,index:number)=>void}){const list=flowNodes(resource);return <div className="mk-flow-map" aria-label={`${resource.name} automation map`}>{list.map((n,i)=>{const body=<><span className="mk-flow-icon">{icon[n.kind]}</span><div><strong>{n.label}</strong>{n.detail&&<small>{n.detail}</small>}</div>{n.kind==="condition"&&<span className="mk-flow-branches"><i>Yes</i><i>No</i></span>}{i<list.length-1&&<span className="mk-flow-line" aria-hidden="true"/>}</>;return onNodeClick?<button type="button" className={`mk-flow-node mk-flow-${n.kind}`} key={`${n.label}-${i}`} onClick={()=>onNodeClick(n,i)}>{body}</button>:<div className={`mk-flow-node mk-flow-${n.kind}`} key={`${n.label}-${i}`}>{body}</div>})}</div>}
