"use client";
import { useState } from "react";
import { Content, defaultContent } from "@/lib/marketing/rules";
type Step={minutes:number;subject:string;channel:string;content:Content};
type Data={reviewed?:boolean;description?:string;steps:Step[];smsContent?:Content};
type Resource={key:string;name:string;enabled:boolean;data:Record<string,unknown>};
export default function FlowEditor({resource,busy,save}:{resource:Resource;busy:boolean;save:(data:Data,enabled:boolean)=>void}){
 const initial=resource.data as unknown as Data; const [flow,setFlow]=useState<Data>(()=>JSON.parse(JSON.stringify(initial))); const [enabled,setEnabled]=useState(resource.enabled);
 const step=(i:number,k:string,v:unknown)=>setFlow(f=>({...f,steps:f.steps.map((s,n)=>n===i?{...s,[k]:v}:s)}));
 const content=(i:number,k:keyof Content,v:string)=>setFlow(f=>({...f,steps:f.steps.map((s,n)=>n===i?{...s,content:{...s.content,[k]:v}}:s)}));
 const fields=(c:Content,on:(k:keyof Content,v:string)=>void)=><><label>Message heading<input value={c.heading||""} onChange={e=>on("heading",e.target.value)}/></label><label>Message<textarea rows={4} value={c.body||""} onChange={e=>on("body",e.target.value)}/></label><div className="mk-two"><label>Button text<input value={c.button||""} onChange={e=>on("button",e.target.value)}/></label><label>Button destination<input value={c.url||""} onChange={e=>on("url",e.target.value)}/></label></div></>;
 const sms=(k:keyof Content,v:string)=>setFlow(f=>({...f,smsContent:{...(f.smsContent||defaultContent),[k]:v}}));
 return <article className="mk-panel"><h2>Edit {resource.name}</h2><p>{flow.description}</p><div className="mk-flow-note"><strong>How this works</strong><span>Each message waits the number of minutes shown after the trigger. Before sending, Reef Ops checks consent, suppression, audience rules, and purchase status.</span></div><h3>Messages</h3>{flow.steps.map((s,i)=><fieldset className="mk-flow-step" key={i}><legend>Message {i+1}</legend><div className="mk-two"><label>Wait after trigger (minutes)<input type="number" min="0" value={s.minutes} onChange={e=>step(i,"minutes",Number(e.target.value))}/></label><label>Channel<select value={s.channel} onChange={e=>step(i,"channel",e.target.value)}><option value="EMAIL">Email</option><option value="SMS_MARKETING">SMS marketing</option><option value="SMS_TRANSACTIONAL">SMS transactional</option></select></label></div>{fields(s.content,(k,v)=>content(i,k,v))}</fieldset>)}{resource.key==="abandoned-cart"&&<fieldset className="mk-flow-step"><legend>Optional SMS branch</legend><p>This is sent 30 minutes after checkout only when SMS marketing consent, a valid timezone, and no purchase are present.</p>{fields(flow.smsContent||defaultContent,sms)}</fieldset>}<label className="mk-check"><input type="checkbox" checked={!!flow.reviewed} onChange={e=>setFlow({...flow,reviewed:e.target.checked})}/>I reviewed the messages, timing, consent rules, and purchase checks.</label><label className="mk-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable this flow</label><div className="mk-actions"><button disabled={busy} onClick={()=>save(flow,enabled)}>Save flow</button></div></article>;
}
